/* eslint-disable */
/**
 * Generated by Convex — stub for frontend development.
 * This file will be overwritten when the backend is deployed.
 */

import { anyApi } from "convex/server";

export const api = anyApi as any;
export const internal = anyApi as any;
